/**
 * `rainbowindex generate-snapshot` — the non-Vite path to a theme-aware `ri()`.
 *
 * `ri()` decides whether `text-lg` is a size or a color by asking the published
 * snapshot. A compile publishes one; a browser bundle never runs a compile, so
 * without help every project-defined size, weight, font slot, and color name is
 * unknown and `ri("text-lg text-white")` drops the size.
 *
 * The Vite plugin solves this with a virtual module. Every other bundler gets
 * this: a small generated file, committed or gitignored as you prefer, that
 * publishes the theme the moment it is imported. Import it once at your entry
 * point, above everything else, and the default `ri()` is correct everywhere.
 *
 * The generated module is deterministic — sorted, and derived from the CSS
 * entry alone — so re-running it on an unchanged theme rewrites nothing and
 * produces no diff.
 */

import { relative, resolve } from "node:path";
import { analyzeProjectCSS } from "../project/analyze.js";
import { snapshotFromCSS } from "../project/snapshot.js";
import type { CLIOptions } from "./args.js";
import { writeFileAtomic } from "./atomic-write.js";
import { loadProjectCSS } from "./css-file.js";

/** Default output path, resolved against cwd. */
const SNAPSHOT_FILE = "rainbowindex-snapshot.ts";

export async function generateSnapshot(opts: CLIOptions, cwd: string): Promise<void> {
	const { css, cssFile, warnings } = await loadProjectCSS(opts, cwd);
	for (const warning of warnings) console.error(warning);

	const analysis = analyzeProjectCSS(css);
	for (const warning of analysis.warnings) console.error(warning);

	const snapshot = snapshotFromCSS(css);
	const source = cssFile === null ? "no CSS entry found" : relative(cwd, cssFile);
	const outPath = resolve(cwd, opts.output ?? SNAPSHOT_FILE);

	// JSON.stringify with an indent, embedded as a TS expression: the shape is
	// plain data by construction (serializeSnapshot returns arrays, strings, and
	// a string-keyed record), so there is nothing here a bundler must interpret.
	const body = `/**
 * Generated by \`rainbowindex generate-snapshot\` from ${source}.
 * Do not edit. Re-run the command when the theme changes.
 *
 * Import this once, as early as possible in your entry point:
 *
 *   import "./${relative(cwd, outPath).split("\\\\").join("/")}";
 *
 * That publishes the theme, so the default \`ri()\` resolves your project's
 * text sizes, weights, font slots, and color names. Without it \`ri()\` has no
 * theme and can read a size as a color and drop it.
 *
 * For multi-tenant rendering — more than one theme in one process — import
 * \`ri\` from here instead of from "rainbowindex": it is bound to this snapshot
 * and shares no module state.
 */
import { createRi, hydrateSnapshot, publishSnapshot } from "rainbowindex";

export const snapshot = hydrateSnapshot(${JSON.stringify(snapshot, null, "\t")});

publishSnapshot(snapshot);

export const ri = createRi(snapshot);
`;

	await writeFileAtomic(outPath, body);
	console.log(`[rainbowindex] Wrote: ${relative(cwd, outPath)}`);
}
