/**
 * Markdown rendering for a results document.
 *
 * One table per size, engines as rows, scenarios as columns — the shape that
 * answers "which is faster on my codebase" without the reader having to hold
 * three numbers in their head.
 */

/** @param {number} ms */
function ms(value) {
	if (value === undefined || value === null || Number.isNaN(value)) return "—";
	if (value >= 1000) return `${(value / 1000).toFixed(2)} s`;
	if (value >= 10) return `${value.toFixed(0)} ms`;
	return `${value.toFixed(2)} ms`;
}

/** @param {number} bytes */
function kb(bytes) {
	if (bytes === undefined || bytes === null) return "—";
	if (bytes >= 1024 * 1024) return `${(bytes / 1024 / 1024).toFixed(2)} MB`;
	return `${(bytes / 1024).toFixed(0)} KB`;
}

/** @param {number} kbytes */
function mb(kbytes) {
	if (!kbytes) return "—";
	return `${(kbytes / 1024).toFixed(0)} MB`;
}

/** Right-pad every cell so the raw markdown is readable in a diff. */
function renderTable(header, rows) {
	const widths = header.map((h, i) => Math.max(h.length, ...rows.map((r) => String(r[i]).length)));
	const line = (cells) => `| ${cells.map((c, i) => String(c).padEnd(widths[i])).join(" | ")} |`;
	return [
		line(header),
		`| ${widths.map((w) => "-".repeat(w)).join(" | ")} |`,
		...rows.map(line),
	].join("\n");
}

/**
 * @param {import("./run.mjs").BenchDocument} doc
 */
export function renderMarkdown(doc) {
	const out = [];
	out.push(`# Benchmark results — ${doc.date}`);
	out.push("");
	out.push(
		`Generated by [\`bench/\`](../README.md) on ${doc.env.platform}/${doc.env.arch}, ` +
			`Node ${doc.env.node}, ${doc.env.cpus}× ${doc.env.cpu}. ` +
			`Reproduce with \`pnpm bench --sizes=${doc.sizes.join(",")}\`.`,
	);
	out.push("");
	out.push("Engines under test:");
	out.push("");
	for (const engine of doc.engines) {
		out.push(`- **${engine.label}** \`${engine.version}\``);
	}
	out.push("");

	for (const size of doc.sizes) {
		const rows = doc.rows.filter((r) => r.size === size);
		if (rows.length === 0) continue;
		const files = rows[0].files;
		const bytes = rows[0].sourceBytes;
		out.push(`## ${size} — ${files.toLocaleString("en-US")} files, ${kb(bytes)} of source`);
		out.push("");
		out.push(
			renderTable(
				[
					"Engine",
					"Cold build",
					"Rebuild (unchanged)",
					"Rebuild (1 file)",
					"Scan only",
					"Output",
					"Peak RSS",
					"Coverage",
				],
				rows.map((r) => [
					r.label,
					ms(r.coldMs),
					ms(r.tasks?.["rebuild-unchanged"]?.medianMs),
					ms(r.tasks?.["rebuild-incremental"]?.medianMs),
					ms(r.tasks?.scan?.medianMs),
					kb(r.minifiedBytes),
					mb(r.maxRssKb),
					`${((100 * r.covered) / r.coverageOf).toFixed(1)}%`,
				]),
			),
		);
		out.push("");
		const missing = rows.filter((r) => r.covered < r.coverageOf);
		if (missing.length > 0) {
			out.push(
				`Coverage is the share of the ${rows[0].coverageOf.toLocaleString("en-US")} distinct ` +
					`classes in the fixture tree that the engine emitted a rule for. Below 100% means ` +
					`the engine does not implement some of them: ` +
					missing.map((r) => `${r.label} is missing ${r.coverageOf - r.covered}`).join(", ") +
					`.`,
			);
			out.push("");
		}
	}

	out.push("## Method");
	out.push("");
	out.push(
		"- **Cold build** is a fresh process each sample: read the tree off disk, construct the " +
			"engine, produce the stylesheet. The figure is the fastest of " +
			`${doc.coldRuns} runs, because noise on a cold start only ever adds.`,
	);
	out.push(
		"- **Rebuild** figures are medians from [tinybench](https://github.com/tinylibs/tinybench) " +
			"against an already-warm engine, the state a dev server is in when you save a file. " +
			"The incremental case changes one file's classes on every iteration, so no iteration " +
			"but the first can be served from a candidate cache.",
	);
	out.push("- **Scan only** is each engine's own public extraction path with no CSS generated.");
	out.push(
		"- **Output** is minified by the same LightningCSS pass for all three, targeting one " +
			"modern browser baseline, so the byte counts are comparable.",
	);
	out.push("- **Peak RSS** is `process.resourceUsage().maxRSS` for the cold-build process.");
	out.push("");
	return `${out.join("\n")}\n`;
}
