import type { ReactNode } from "react";
// The snapshot teaches the browser copy of `ri()` about this project's theme,
// so a client component merging `bg-brand-500` against `bg-brand-700` resolves
// them as conflicting rather than keeping both. Generated by the `prebuild`
// script; import it once, as early as possible.
import "./rainbowindex-snapshot";
import "./styles.css";

export const metadata = { title: "Rainbow Index + Next.js" };

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang="en">
			<body className="min-h-screen bg-gray-50">{children}</body>
		</html>
	);
}
